import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Translate from "./component/layout/Translate";
import Header from "./component/layout/Header";
import Ontop from "./component/layout/Ontop";
import Footer from "./component/layout/Footer";
import Slider from "./component/layout/Slider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {/* <Translate /> */}
        <Header />
        {children}
        <Ontop />
        <Slider />
        <Footer />
        <Script
              src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
              strategy="afterInteractive"
            />
      </body>
    </html>
  );
}
